#!/bin/bash
# Generate fresh deterministic test credentials and write them to source/.env.test
#
# Run this when you want a completely new set of test keys.
# After running, commit the updated .env.test to lock in the new credentials.
#
# Usage:
#   cd source
#   ./scripts/generate-test-credentials.sh
#
# Requirements:
#   - aptos CLI must be installed and on PATH (or pass APTOS_BIN=/path/to/aptos)
#   - Alternatively: run inside the validator Docker image which has the aptos CLI
#
# After regenerating you must also:
#   1. Update the genesis-workspace by running a fresh testnet (bun run testnet)
#   2. The new public keys will appear in docker-testnet/genesis-workspace/validator-*/public-keys.yaml
#   3. Copy the public keys back into .env.test (or re-run this script with --with-public-keys)
set -e

APTOS_BIN="${APTOS_BIN:-aptos}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_TEST="${SCRIPT_DIR}/../.env.test"
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

if ! command -v "$APTOS_BIN" &>/dev/null; then
    echo "ERROR: aptos CLI not found. Set APTOS_BIN=/path/to/aptos or install it."
    echo "  Tip: run this inside the validator Docker image:"
    echo "    docker run --rm -it -v \$(pwd):/source <validator-image> bash /source/scripts/generate-test-credentials.sh"
    exit 1
fi

echo "Generating fresh test credentials..."
echo "Output: $ENV_TEST"
echo ""

generate_keys() {
    local name="$1"
    local outdir="$TMPDIR/$name"
    mkdir -p "$outdir"
    "$APTOS_BIN" genesis generate-keys --output-dir "$outdir" --assume-yes > /dev/null 2>&1
    echo "$outdir"
}

# Generate root account
echo "Generating root account..."
ROOT_DIR=$(generate_keys "root")
ROOT_ADDR=$(grep "account_address:" "$ROOT_DIR/private-keys.yaml" | awk '{print $2}')
ROOT_PK=$(grep "account_private_key:" "$ROOT_DIR/private-keys.yaml" | awk '{print $2}' | tr -d '"')
ROOT_PUB=$(grep "account_public_key:" "$ROOT_DIR/public-keys.yaml" | awk '{print $2}' | tr -d '"')

# Generate deployer account
echo "Generating deployer account..."
DEPLOYER_DIR=$(generate_keys "deployer")
DEPLOYER_ADDR=$(grep "account_address:" "$DEPLOYER_DIR/private-keys.yaml" | awk '{print $2}')
DEPLOYER_PK=$(grep "account_private_key:" "$DEPLOYER_DIR/private-keys.yaml" | awk '{print $2}' | tr -d '"')

# Generate validator accounts
declare -A VAL_ADDR VAL_ACCT_PK VAL_ACCT_PUB VAL_CONS_PK VAL_CONS_PUB VAL_CONS_POP VAL_FN_PK VAL_FN_PUB VAL_NET_PK VAL_NET_PUB
for i in 0 1 2 3; do
    echo "Generating validator $i..."
    DIR=$(generate_keys "validator-$i")
    VAL_ADDR[$i]=$(grep "account_address:" "$DIR/private-keys.yaml" | awk '{print $2}')
    VAL_ACCT_PK[$i]=$(grep "account_private_key:" "$DIR/private-keys.yaml" | awk '{print $2}' | tr -d '"')
    VAL_ACCT_PUB[$i]=$(grep "account_public_key:" "$DIR/public-keys.yaml" | awk '{print $2}' | tr -d '"')
    VAL_CONS_PK[$i]=$(grep "consensus_private_key:" "$DIR/private-keys.yaml" | awk '{print $2}' | tr -d '"')
    VAL_CONS_PUB[$i]=$(grep "consensus_public_key:" "$DIR/public-keys.yaml" | awk '{print $2}' | tr -d '"')
    VAL_CONS_POP[$i]=$(grep "consensus_proof_of_possession:" "$DIR/public-keys.yaml" | awk '{print $2}' | tr -d '"')
    VAL_FN_PK[$i]=$(grep "full_node_network_private_key:" "$DIR/private-keys.yaml" | awk '{print $2}' | tr -d '"')
    VAL_FN_PUB[$i]=$(grep "full_node_network_public_key:" "$DIR/public-keys.yaml" | awk '{print $2}' | tr -d '"')
    VAL_NET_PK[$i]=$(grep "validator_network_private_key:" "$DIR/private-keys.yaml" | awk '{print $2}' | tr -d '"')
    VAL_NET_PUB[$i]=$(grep "validator_network_public_key:" "$DIR/public-keys.yaml" | awk '{print $2}' | tr -d '"')
done

cat > "$ENV_TEST" <<EOF
# =============================================================================
# Test credentials — committed, deterministic, used by all packages.
#
# Generated by: source/scripts/generate-test-credentials.sh
# Loaded automatically by Vite/Vitest in test mode (envDir points here).
# Non-Vite Node scripts load this via bun --env-file=../.env.test.
# =============================================================================

# -----------------------------------------------------------------------------
# Aptos — root account (faucet / funder)
# -----------------------------------------------------------------------------
APTOS_ROOT_ACCOUNT_ADDRESS=0x${ROOT_ADDR}
APTOS_ROOT_ACCOUNT_PRIVATE_KEY=${ROOT_PK}
APTOS_ROOT_ACCOUNT_PUBLIC_KEY=${ROOT_PUB}

# -----------------------------------------------------------------------------
# Aptos — contract deployer
# -----------------------------------------------------------------------------
APTOS_DEPLOYER_ADDRESS=0x${DEPLOYER_ADDR}
APTOS_DEPLOYER_PRIVATE_KEY=${DEPLOYER_PK}
APTOS_ATOMICA_CONTRACT_ADDRESS=0x${DEPLOYER_ADDR}

# -----------------------------------------------------------------------------
# Aptos — validator 0
# -----------------------------------------------------------------------------
APTOS_VALIDATOR_0_ACCOUNT_ADDRESS=0x${VAL_ADDR[0]}
APTOS_VALIDATOR_0_ACCOUNT_PRIVATE_KEY=${VAL_ACCT_PK[0]}
APTOS_VALIDATOR_0_ACCOUNT_PUBLIC_KEY=${VAL_ACCT_PUB[0]}
APTOS_VALIDATOR_0_CONSENSUS_PRIVATE_KEY=${VAL_CONS_PK[0]}
APTOS_VALIDATOR_0_CONSENSUS_PUBLIC_KEY=${VAL_CONS_PUB[0]}
APTOS_VALIDATOR_0_CONSENSUS_PROOF_OF_POSSESSION=${VAL_CONS_POP[0]}
APTOS_VALIDATOR_0_FULL_NODE_NETWORK_PRIVATE_KEY=${VAL_FN_PK[0]}
APTOS_VALIDATOR_0_FULL_NODE_NETWORK_PUBLIC_KEY=${VAL_FN_PUB[0]}
APTOS_VALIDATOR_0_VALIDATOR_NETWORK_PRIVATE_KEY=${VAL_NET_PK[0]}
APTOS_VALIDATOR_0_VALIDATOR_NETWORK_PUBLIC_KEY=${VAL_NET_PUB[0]}

# -----------------------------------------------------------------------------
# Aptos — validator 1
# -----------------------------------------------------------------------------
APTOS_VALIDATOR_1_ACCOUNT_ADDRESS=0x${VAL_ADDR[1]}
APTOS_VALIDATOR_1_ACCOUNT_PRIVATE_KEY=${VAL_ACCT_PK[1]}
APTOS_VALIDATOR_1_ACCOUNT_PUBLIC_KEY=${VAL_ACCT_PUB[1]}
APTOS_VALIDATOR_1_CONSENSUS_PRIVATE_KEY=${VAL_CONS_PK[1]}
APTOS_VALIDATOR_1_CONSENSUS_PUBLIC_KEY=${VAL_CONS_PUB[1]}
APTOS_VALIDATOR_1_CONSENSUS_PROOF_OF_POSSESSION=${VAL_CONS_POP[1]}
APTOS_VALIDATOR_1_FULL_NODE_NETWORK_PRIVATE_KEY=${VAL_FN_PK[1]}
APTOS_VALIDATOR_1_FULL_NODE_NETWORK_PUBLIC_KEY=${VAL_FN_PUB[1]}
APTOS_VALIDATOR_1_VALIDATOR_NETWORK_PRIVATE_KEY=${VAL_NET_PK[1]}
APTOS_VALIDATOR_1_VALIDATOR_NETWORK_PUBLIC_KEY=${VAL_NET_PUB[1]}

# -----------------------------------------------------------------------------
# Aptos — validator 2
# -----------------------------------------------------------------------------
APTOS_VALIDATOR_2_ACCOUNT_ADDRESS=0x${VAL_ADDR[2]}
APTOS_VALIDATOR_2_ACCOUNT_PRIVATE_KEY=${VAL_ACCT_PK[2]}
APTOS_VALIDATOR_2_ACCOUNT_PUBLIC_KEY=${VAL_ACCT_PUB[2]}
APTOS_VALIDATOR_2_CONSENSUS_PRIVATE_KEY=${VAL_CONS_PK[2]}
APTOS_VALIDATOR_2_CONSENSUS_PUBLIC_KEY=${VAL_CONS_PUB[2]}
APTOS_VALIDATOR_2_CONSENSUS_PROOF_OF_POSSESSION=${VAL_CONS_POP[2]}
APTOS_VALIDATOR_2_FULL_NODE_NETWORK_PRIVATE_KEY=${VAL_FN_PK[2]}
APTOS_VALIDATOR_2_FULL_NODE_NETWORK_PUBLIC_KEY=${VAL_FN_PUB[2]}
APTOS_VALIDATOR_2_VALIDATOR_NETWORK_PRIVATE_KEY=${VAL_NET_PK[2]}
APTOS_VALIDATOR_2_VALIDATOR_NETWORK_PUBLIC_KEY=${VAL_NET_PUB[2]}

# -----------------------------------------------------------------------------
# Aptos — validator 3
# -----------------------------------------------------------------------------
APTOS_VALIDATOR_3_ACCOUNT_ADDRESS=0x${VAL_ADDR[3]}
APTOS_VALIDATOR_3_ACCOUNT_PRIVATE_KEY=${VAL_ACCT_PK[3]}
APTOS_VALIDATOR_3_ACCOUNT_PUBLIC_KEY=${VAL_ACCT_PUB[3]}
APTOS_VALIDATOR_3_CONSENSUS_PRIVATE_KEY=${VAL_CONS_PK[3]}
APTOS_VALIDATOR_3_CONSENSUS_PUBLIC_KEY=${VAL_CONS_PUB[3]}
APTOS_VALIDATOR_3_CONSENSUS_PROOF_OF_POSSESSION=${VAL_CONS_POP[3]}
APTOS_VALIDATOR_3_FULL_NODE_NETWORK_PRIVATE_KEY=${VAL_FN_PK[3]}
APTOS_VALIDATOR_3_FULL_NODE_NETWORK_PUBLIC_KEY=${VAL_FN_PUB[3]}
APTOS_VALIDATOR_3_VALIDATOR_NETWORK_PRIVATE_KEY=${VAL_NET_PK[3]}
APTOS_VALIDATOR_3_VALIDATOR_NETWORK_PUBLIC_KEY=${VAL_NET_PUB[3]}

# -----------------------------------------------------------------------------
# Vite compile-time constants (injected into browser bundle as import.meta.env)
# -----------------------------------------------------------------------------
VITE_CONTRACT_ADDRESS=0x${DEPLOYER_ADDR}
VITE_ETH_RPC_URL=http://localhost:8545
VITE_FAKE_ETH_ADDRESS=0x0000000000000000000000000000000000000000
VITE_FAKE_USD_ADDRESS=0x0000000000000000000000000000000000000000
VITE_LOCK_BOX_ADDRESS=0x0000000000000000000000000000000000000000

# -----------------------------------------------------------------------------
# Ethereum — deployer (Hardhat deterministic account 0)
# These are fixed by Hardhat's BIP-39 mnemonic and do not need regeneration.
# -----------------------------------------------------------------------------
ETHEREUM_DEPLOYER_ADDRESS=0x8943545177806ED17B9F23F0a21ee5948eCaa776
ETHEREUM_DEPLOYER_PRIVATE_KEY=0xbcdf20249abf0ed6d944c0288fad489e33f66b3960d9e6229c1cd214ed3bbe31
ETHEREUM_DEPLOYER_MNEMONIC=giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete

# -----------------------------------------------------------------------------
# Ethereum — account 0 (Hardhat default)
# -----------------------------------------------------------------------------
ETHEREUM_ACCOUNT_0_ADDRESS=0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
ETHEREUM_ACCOUNT_0_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
EOF

echo ""
echo "Done! New credentials written to: $ENV_TEST"
echo ""
echo "Next steps:"
echo "  1. Run: bun run testnet  (to regenerate genesis with new keys)"
echo "  2. Commit the updated .env.test"
