name: Lint Web Packages

on:
  pull_request:
    
    paths:
      - 'source/atomica-sdk/**'
      - 'source/atomica-web-components/**'
      - 'source/atomica-demo/**'
      - '.github/workflows/lint-web.yaml'
  push:
    
    paths:
      - 'source/atomica-sdk/**'
      - 'source/atomica-web-components/**'
      - 'source/atomica-demo/**'
      - '.github/workflows/lint-web.yaml'
  workflow_dispatch:

jobs:
  lint-sdk:
    name: Lint SDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        working-directory: source/atomica-sdk
        run: bun install

      - name: Lint
        working-directory: source/atomica-sdk
        run: bun run lint

      - name: Format Check
        working-directory: source/atomica-sdk
        run: bun run format:check

      - name: Type Check
        working-directory: source/atomica-sdk
        run: bun run build

  lint-web-ui:
    name: Lint Web UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build Ethereum Testnet SDK
        working-directory: source/docker-testnet/ethereum-testnet/typescript-sdk
        run: |
          bun install
          bun run build

      - name: Build Atomica SDK
        working-directory: source/atomica-sdk
        run: |
          bun install
          bun run build

      - name: Build State Proofs
        working-directory: source/state-proofs/typescript
        run: |
          bun install
          bun run build

      - name: Build Aptos Testnet SDK
        working-directory: source/docker-testnet/aptos-testnet
        run: |
          bun install
          bun run build

      - name: Install dependencies
        working-directory: source/atomica-web-components
        run: bun install

      - name: Lint
        working-directory: source/atomica-web-components
        run: bun run lint

      - name: Format Check
        working-directory: source/atomica-web-components
        run: bun run format:check

      - name: Type Check
        working-directory: source/atomica-web-components
        run: bun run build

  lint-web-demo:
    name: Lint Web Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build Ethereum Testnet SDK
        working-directory: source/docker-testnet/ethereum-testnet/typescript-sdk
        run: |
          bun install
          bun run build

      - name: Build Atomica SDK
        working-directory: source/atomica-sdk
        run: |
          bun install
          bun run build

      - name: Build State Proofs
        working-directory: source/state-proofs/typescript
        run: |
          bun install
          bun run build

      - name: Build Aptos Testnet SDK
        working-directory: source/docker-testnet/aptos-testnet
        run: |
          bun install
          bun run build

      - name: Build Web UI
        working-directory: source/atomica-web-components
        run: |
          bun install
          bun run build

      - name: Install dependencies
        working-directory: source/atomica-demo
        run: bun install

      - name: Lint
        working-directory: source/atomica-demo
        run: bun run lint

      - name: Format Check
        working-directory: source/atomica-demo
        run: bun run format:check

      - name: Type Check
        working-directory: source/atomica-demo
        run: bun run build
